name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      
      - name: Build binaries
        run: |
          # macOS
          GOOS=darwin GOARCH=amd64 go build -o kawa-darwin-amd64 -ldflags="-s -w" .
          GOOS=darwin GOARCH=arm64 go build -o kawa-darwin-arm64 -ldflags="-s -w" .
          
          # Linux
          GOOS=linux GOARCH=amd64 go build -o kawa-linux-amd64 -ldflags="-s -w" .
          GOOS=linux GOARCH=arm64 go build -o kawa-linux-arm64 -ldflags="-s -w" .
          
          # Windows
          GOOS=windows GOARCH=amd64 go build -o kawa-windows-amd64.exe -ldflags="-s -w" .
      
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kawa-darwin-amd64
            kawa-darwin-arm64
            kawa-linux-amd64
            kawa-linux-arm64
            kawa-windows-amd64.exe
          generate_release_notes: true